### ISSUE TITLE
Is it possible to build the bootstrap compiler?

### ISSUE THREAD

**Issue by ghost** [m2sf/m2bsk#3]
I've been using gnu modula-2 over vacation and enjoying it very much. I'm intrigued by some of the newer generic and object extensions mentioned on Rick Sutcliffe's excellent Modula-2: Abstractions for Data and Programming Structures but can't find a compiler that supports the full range of that document's content and am searching for a compiler that is up to the task.

**Comment by trijezdci** [comment]
Hi there, the compiler is work in progress.

We are currently reviewing the format specifiers of the IO library which is the final item before freezing the specification, this should be complete this month and we will then resume work on the compiler.

The present version of Rick's book describes ISO Modula-2, a different dialect. 

Our revision of the language handles generic and object-oriented programming in a different way.

The only ISO M2 compiler that supports the generic and object-oriented extensions is the p1 compiler. It is only available for MacOS.
