### ISSUE TITLE
Misslng Lexeme.{def,mod} files

### ISSUE THREAD

**Issue by vonbrand** [m2sf/m2bsk#4]
Nowhere to be found in the repository.

**Comment by trijezdci** [comment]
A lexeme is a string and strings are implemented in library `String`. https://github.com/m2sf/m2bsk/blob/master/src/lib/String.def

If there are any imports of a library called `Lexeme`, this is an artefact and will need to be renamed to `String`.

**Comment by trijezdci** [comment]
All instances of LexemeT renamed to StringT.
